# Generated by go2rpm 1
%bcond_without check

# https://github.com/GehirnInc/crypt
%global goipath         github.com/GehirnInc/crypt
%global commit          6c0105aabd460ae06c87afeb5a47c869f6a7557e

%gometa

%global common_description %{expand:
Pure Go crypt(3) Implementation.}

%global golicenses      LICENSE
%global godocs          README.rst AUTHORS.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Pure Go crypt(3) Implementation

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Nov 13 12:21:07 UTC 2019 mockbuild - 0-0.1.20191113git6c0105a
- Initial package

